# Generated by Django 5.2.6 on 2025-10-23 01:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['data_prazo', '-prioridade', '-peso']},
        ),
        migrations.RenameField(
            model_name='atividade',
            old_name='dataPrazo',
            new_name='data_prazo',
        ),
        migrations.AddField(
            model_name='atividade',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atividade',
            name='categoria',
            field=models.CharField(choices=[('PROVA', 'Prova'), ('TAREFA', 'Tarefa'), ('SEMINARIO', 'Seminário')], default='TAREFA', max_length=15),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='estudos.disciplina'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='estimativa_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='local',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='modalidade',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online')], default='ONLINE', max_length=12),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='peso',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['usuario', 'data_prazo'], name='estudos_ati_usuario_104114_idx'),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['disciplina'], name='estudos_ati_discipl_b49c5f_idx'),
        ),
    ]
