# Generated by Django 5.2.7 on 2025-11-11 22:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0002_delete_meta_delete_notificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
