# Generated by Django 5.2.6 on 2025-11-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0003_disciplina_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='prioridade',
            field=models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=2),
        ),
    ]
