# Generated by Django 5.2.6 on 2025-11-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0005_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
