# Generated by Django 5.2.6 on 2025-11-18 17:50

from django.db import migrations
from django.contrib.auth.models import User

class Migration(migrations.Migration):
    def generate_superuser(*_):
        from django.contrib.auth.models import User

        try:
            User.objects.create_superuser('admin', 'admin@example.com', '123').save()
        except:
            pass

    atomic = False
        
    dependencies = [
        ('estudos', '0006_alter_meta_descricao'),
    ]

    operations = [
        migrations.RunPython(generate_superuser)
    ]
