# Generated by Django 5.2.6 on 2025-11-20 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0008_sessao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessao',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='sessao',
            name='meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='estudos.meta'),
        ),
    ]
