# Generated by Django 5.2.6 on 2025-11-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0009_remove_sessao_disciplina_sessao_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='nome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
