# Generated by Django 5.2.6 on 2025-11-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0010_meta_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='data_final',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='data_inicial',
        ),
    ]
