# Generated by Django 5.2.6 on 2025-11-20 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0011_remove_meta_data_final_remove_meta_data_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
